# Clash 基础配置
clash:
  port: 7890
  socks-port: 7891
  allow-lan: true
  mode: Rule
  log-level: info
  external-controller: ":9090"

# 缓存配置
cache:
  type: FileSystemCache
  dir: /tmp/clash_conf/
  timeout: 3000
  node_timeout: 300

# 测试配置
test_url: http://www.gstatic.com/generate_204
test_interval: 300
test_tolerance: 50

# 过滤关键词
exclude_keywords:
  - 剩余
  - 套餐
  - 官网
  - 流量
  - 群组 